name: whatsapp_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0
#'>=3.1.0-292.0.dev <4.0.0'
environment:
  sdk: '>=3.1.0-292.0.dev <4.0.0'
dependencies:
  audioplayers: ^5.1.0
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  cloud_firestore: ^4.8.4
  country_picker: ^2.0.20
  emoji_picker_flutter: ^1.6.1
  enough_giphy_flutter: ^0.4.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7+1
  flutter_riverpod: ^2.3.6
  flutter_sound: ^9.2.13
  image_picker: ^1.0.2
  intl: ^0.18.1
  path_provider: ^2.1.1
  permission_handler: ^9.2.0
  swipe_to: ^1.0.2
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/backgroundImage.png
    - assets/bg.png